Repository 18F/handbook, pull requests merged in 2019-10, with the labels that each got.

#1572 Create "Guidance on hosting non-government speakers" page
  _pages/policies/employee-resources-policies/hosting-non-government-speakers
Labels: 2-4 hours, new content needed

#1397 Update travel-guide-faq.md
  _pages/policies/travel-and-leave-policies/travel-guide-faq.md
Labels: changes requested

#1443 Removed GSA Telework Policy [outdated]
  _pages/policies/employee-resources-policies/telework.md
Labels: changes requested

#1446 Add-Assisted-Acq-Info
  _pages/about-us/teams/oa.md
Labels: changes requested

#1467 Update benefits.md
  _pages/welcome-to-TTS/classes/benefits.md
Labels: technical problem

#1468 Update benefits-links.md
  _pages/policies/employee-resources-policies/benefits-links.md
Labels: technical problem

#1494 Update employment-verification.md
  _pages/policies/employee-resources-policies/employment-verification.md
Labels: changes requested

#1517 Update agreements.md
  _pages/how-we-work/agreements.md
Labels: changes requested
