Repository 18F/handbook, pull requests merged in 2021-11, with the labels that each got.

#2902 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/pending_publish

#2903 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2904 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2907 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2912 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2915 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2899 Update page “general-information-and-resources/employee-resources-policies/deaf-hoh”
  _pages/general-information-and-resources/employee-resources-policies/deaf-hoh.md
Labels: netlify-cms/draft

#2885 Update page “tools/slack/getting-started”
  _pages/tools/slack/getting-started.md
Labels: netlify-cms/draft

#2887 Update page “tools/slack/records”
  _pages/tools/slack/records.md
Labels: netlify-cms/draft

#2893 Update page “general-information-and-resources/employee-resources-policies/benefits-links”
  _pages/general-information-and-resources/employee-resources-policies/benefits-links.md
Labels: netlify-cms/draft

#2920 Update page “getting-started/classes”
  _pages/getting-started/classes.md
Labels: netlify-cms/pending_review

#2926 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2929 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2923 Remove weekly all-hands meeting references from Distributed teams page
  _pages/general-information-and-resources/distributed.md
Labels: help wanted

#2836 Update page “about-us/tts-history”
  _pages/about-us/tts-history.md
Labels: netlify-cms/draft

#2888 Create page “tools/channels/index”
  _pages/tools/channels/index.md
Labels: netlify-cms/draft

#2935 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft
