Repository 18F/handbook, pull requests merged in 2021-09, with the labels that each got.

#2798 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2797 add exception around GSA staff PII
  _pages/general-information-and-resources/sensitive-information.md
Labels: netlify-cms/pending_review

#2808 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2812 Update page “hiring-staying-or-changing-jobs/assignee-detail”
  _pages/hiring-staying-or-changing-jobs/assignee-detail.md
Labels: netlify-cms/draft

#2813 Update page “hiring-staying-or-changing-jobs/assignee-detail”
  _pages/hiring-staying-or-changing-jobs/assignee-detail.md
Labels: netlify-cms/draft

#2815 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2816 Update Benefits TSP section for 2021 annual limits
  _pages/getting-started/classes/benefits.md
Labels: info is incorrect/outdated

#2817 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2801 Update page “tools/slack/user-management”
  _pages/tools/slack/user-management.md
Labels: netlify-cms/pending_review

#2803 Update page “tools/slack/guidelines”
  _pages/tools/slack/guidelines.md
Labels: netlify-cms/draft

#2804 Update page “tools/slack/integrations”
  _pages/tools/slack/integrations.md
Labels: netlify-cms/draft

#2787 Update voucher procedure.
  _pages/travel-and-leave/travel-and-leave-policies/travel-guide-3-reimbursement.md
Labels: netlify-cms/pending_review

#2818 Update page “performance-management/index”
  _pages/performance-management/index.md
Labels: netlify-cms/draft

#2819 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2820 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2827 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2823 Update Other “contributing”
  CONTRIBUTING.md
Labels: netlify-cms/draft

#2831 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2830 Update page “performance-management/index”
  _pages/performance-management/index.md
Labels: netlify-cms/draft

#2807 Update page “performance-management/supervisor-resources”
  _pages/performance-management/supervisor-resources.md
Labels: netlify-cms/draft

#2837 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2839 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft
