Repository 18F/handbook, pull requests merged in 2022-08, with the labels that each got.

#3173 Update page “hiring-staying-or-changing-jobs/assignee-detail”
  _pages/hiring-staying-or-changing-jobs/assignee-detail.md
Labels: netlify-cms/draft

#3172 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3175 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/pending_publish

#3179 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3183 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3184 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3185 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3186 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3188 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3192 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3193 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3196 Update OPP to Solutions
  _pages/about-us/tts-history.md
Labels: page update

#3197 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3198 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft
