Repository 18F/handbook, pull requests merged in 2022-01, with the labels that each got.

#2954 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2955 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2957 Update page “performance-management/index”
  _pages/performance-management/index.md
Labels: netlify-cms/pending_review

#2958 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2959 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2961 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2966 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2967 Update page “hiring-staying-or-changing-jobs/term-extensions”
  _pages/hiring-staying-or-changing-jobs/term-extensions.md
Labels: netlify-cms/draft

#2968 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2972 Update page “hiring-staying-or-changing-jobs/term-extensions”
  _pages/hiring-staying-or-changing-jobs/term-extensions.md
Labels: netlify-cms/draft

#2974 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  _pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#2977 Update page “getting-started/classes”
  _pages/getting-started/classes.md
Labels: netlify-cms/draft

#2981 Update page “getting-started/classes”
  _pages/getting-started/classes.md
Labels: netlify-cms/pending_publish
