Repository 18F/handbook, pull requests merged in 2023-02, with the labels that each got.

#3426 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/pending_review

#3427 Update page “hiring-staying-or-changing-jobs/hiring”
  pages/hiring-staying-or-changing-jobs/hiring.md
Labels: netlify-cms/draft

#3429 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/pending_review

#3431 Update page “18f/how-18f-works/research-guidelines”
  pages/18f/how-18f-works/research-guidelines.md
Labels: netlify-cms/draft

#3444 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/pending_review

#3437 Update classes.md
  pages/getting-started/classes.md
Labels: do not merge yet

#3458 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3461 Update page “hiring-staying-or-changing-jobs/ttsjobs”
  pages/hiring-staying-or-changing-jobs/ttsjobs.md
Labels: netlify-cms/draft

#3464 Update page “hiring-staying-or-changing-jobs/hiring-authorities”
  pages/hiring-staying-or-changing-jobs/hiring-authorities.md
Labels: netlify-cms/draft

#3466 Update page “hiring-staying-or-changing-jobs/hiring-authorities”
  pages/hiring-staying-or-changing-jobs/hiring-authorities.md
Labels: netlify-cms/draft

#3475 Plain language updates to compensation process
  pages/18f/how-18f-works/research-guidelines.md
Labels: Review ready, changes requested, page update
